//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class TransactionController : ICreateTransaction
{
	public virtual Product DB Product DB
	{
		get;
		set;
	}

	public virtual Transaction DB Transaction DB
	{
		get;
		set;
	}

	public virtual Transaction Transaction
	{
		get;
		set;
	}

	public virtual Observer Observer
	{
		get;
		set;
	}

	public virtual string CreateTransaction(object List<Tuple<int, object int>>)
	{
		throw new System.NotImplementedException();
	}

}

